import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import App from "next/app";
import { Appbar } from "@/components/ui/Appbar";
import ParallelogramImageBackground from "@/components/ui/Parallelogram";
import { Button } from "@headlessui/react";
import FAQSection from "@/components/ui/faq";
import Showcase from "@/components/ui/Logoshowcase";
import Pricing from "@/components/ui/pricing";
import AnimatedImageGrid from "@/components/ui/Parallelogram";
import Hero from "@/components/Hero";
import Netflix from "@/components/ui/bgimg";
import ImageCollage from "@/components/ui/collage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div>
      </div>
        {children}
      </body>
      </ClerkProvider>
    </html>
  );
}
