import BoudoirPack from "./ui/Boudoir";
import HingePack from "./ui/Hinge";
import InstagramPack from "./ui/Instagrampack";
import LinkedInHeadshotsPack from "./ui/Linkedinheadshots";
import LuxuryLifestylePack from "./ui/Luxurylifestyle";
import ModelHeadshotsPack from "./ui/Modelheadshots";
import PolaroidPack from "./ui/Polaroid";
import ProfessionalHeadshotsPack from "./ui/Professionalheadshots";
import TinderPack from "./ui/Tinderpack";

export default function PackImages() {
    return (
        <div>
            <h1 className="text-3xl md:text-5xl font-bold text-center mb-8">
        <span className="bg-gradient-to-r from-pink-500 to-purple-500 text-transparent bg-clip-text">
        Get an Idea About How
        </span>{" "}
        Photos Generated by a Particular Pack would look like
      </h1>
            {/* Navigation Links */}
            <nav style={{ position: 'sticky', top: 0, background: '#fff', padding: '10px', zIndex: 1000 }}>
                <ul style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', listStyle: 'none', padding: 0 }}>
                    <li><a href="#tinder" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Tinder Pack</a></li>
                    <li><a href="#instagram" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Instagram Pack</a></li>
                    <li><a href="#model-headshots" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Model Headshots Pack</a></li>
                    <li><a href="#professional-headshots" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Professional Headshots Pack</a></li>
                    <li><a href="#linkedin-headshots" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>LinkedIn Headshots Pack</a></li>
                    <li><a href="#boudoir" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Boudoir Pack</a></li>
                    <li><a href="#hinge" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Hinge Pack</a></li>
                    <li><a href="#polaroid" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Polaroid Pack</a></li>
                    <li><a href="#luxury-lifestyle" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Luxury Lifestyle Pack</a></li>
                </ul>
            </nav>

            {/* Pack Sections */}
            <div id="tinder">
                <TinderPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="instagram">
                <InstagramPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="model-headshots">
                <ModelHeadshotsPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="professional-headshots">
                <ProfessionalHeadshotsPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="boudoir">
                <BoudoirPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="linkedin-headshots">
                <LinkedInHeadshotsPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="hinge">
                <HingePack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="polaroid">
                <PolaroidPack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
            <div id="luxury-lifestyle">
                <LuxuryLifestylePack />
                <a href="#top" style={{ background: 'black', color: 'white', padding: '5px 10px', textDecoration: 'none' }}>Back to top</a>
            </div>
        </div>
    );
}